version: '2'
services:
  
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: shopping-cart
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
    restart: always
